Repository CAU-OSS-2019/team-project-team14, pull requests merged in 2019-05, with the labels that each got.

#12 소스 컴파일 및 실행 API 서버
  api-server/.gitignore
  api-server/README.md
  api-server/server/api/__init__.py
  api-server/server/api/admin.py
  api-server/server/api/apps.py
  api-server/server/api/compile_settings.py
  api-server/server/api/compile_tasks.py
  api-server/server/api/migrations/0001_initial.py
  api-server/server/api/migrations/0002_auto_20190511_1539.py
  api-server/server/api/migrations/0003_code_created_date.py
  api-server/server/api/migrations/0004_auto_20190511_1549.py
  api-server/server/api/migrations/__init__.py
  api-server/server/api/models.py
  api-server/server/api/tests.py
  api-server/server/api/urls.py
  api-server/server/api/views.py
  api-server/server/code/TEMP
  api-server/server/docker-build-full.sh
  api-server/server/docker-run-full.sh
  api-server/server/docker/TEMP
  api-server/server/docker/c/Dockerfile
  api-server/server/docker/c/docker-build.sh
  api-server/server/docker/c/docker-run.sh
  api-server/server/docker/c/exec.sh
  api-server/server/manage.py
  api-server/server/requirements.txt
  api-server/server/server/__init__.py
  api-server/server/server/settings.py
  api-server/server/server/urls.py
  api-server/server/server/wsgi.py
Labels: enhancement

#13 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#15 코드 인식 및 하이라이팅 자동화, 버튼 추가
  Codify/LICENSE
  Codify/background.js
  Codify/buttonStyle.css
  Codify/hljs.js
  Codify/identify.js
  Codify/manifest.json
  highlight-dummy/auto_highlight_dummy.js
Labels: enhancement, provisional

#18 Fix CORS error
  api-server/server/api/urls.py
  api-server/server/requirements.txt
  api-server/server/server/settings.py
Labels: bugfix

#21 Fix compile error when using append to codify
  Codify/connect_extension_and_server.js
  Codify/popup.js
Labels: bugfix, small

#24 C 코드 인식 기능 개선
  Codify/detect.js
Labels: big, enhancement

#26 Enable auto highlight prototype
  Codify/detect.js
Labels: enhancement

#32 컴파일시 stdin(입력) 추가 가능
  api-server/README.md
  api-server/server/api/compile_tasks.py
  api-server/server/api/migrations/0006_source_stdin.py
  api-server/server/api/models.py
  api-server/server/api/views.py
  api-server/server/docker/c/Dockerfile
  api-server/server/docker/c/exec.sh
  api-server/server/docker/cpp/Dockerfile
  api-server/server/docker/cpp/exec.sh
Labels: enhancement

#33 add input textarea and request server with that info
  Codify/connect_extension_and_server.js
  Codify/popup.html
  Codify/popup.js
Labels: enhancement, help wanted

#36 git Pr/add input
  Codify/connect_extension_and_server.js
  Codify/popup.html
Labels: help wanted, small

#37 Change popup design with bootstrap
  Codify/js/jquery-3.4.1.min.js
  Codify/popup.html
  Codify/popup.js
  Codify/style.css
Labels: big

#38 Icon 제작
  Codify/images/banner1.png
  Codify/images/banner2.png
  Codify/images/banner3.png
  Codify/images/banner_vector1.svg
  Codify/images/banner_vector2.svg
  Codify/images/banner_vector3.svg
  Codify/images/get_started128.png
  Codify/images/get_started16.png
  Codify/images/get_started32.png
  Codify/images/get_started48.png
  Codify/images/icon_128.png
  Codify/images/icon_16.png
  Codify/images/icon_32.png
  Codify/images/icon_48.png
  Codify/images/icon_vector.svg
  Codify/manifest.json
  README.md
Labels: small

#39 Pr/add result page
  Codify/result.html
  Codify/result.js
  Codify/style.css
Labels: enhancement, help wanted, small

#44 Fix encoding of txt
  예제링크.txt
Labels: small

#46 인접한 코드 블록을 하나로 합치는 기능 추가
  Codify-cleaned/js/codify/detect.js
  Codify-cleaned/manifest.json
Labels: bugfix, enhancement

#47 코드 컴파일 히스토리 추가
  Codify-cleaned/css/codify/history.css
  Codify-cleaned/html/history.html
  Codify-cleaned/html/popup.html
  Codify-cleaned/html/result.html
  Codify-cleaned/js/codify/detect.js
  Codify-cleaned/js/codify/front_history.js
  Codify-cleaned/js/codify/html_all.js
  Codify-cleaned/js/codify/lib_history.js
  Codify-cleaned/js/codify/nav.js
  Codify-cleaned/js/codify/popup.js
  Codify-cleaned/js/codify/storage.js
  Codify-cleaned/manifest.json
Labels: enhancement

#50 테스트 데이터 분리
  tests/test_page_links.txt
Labels: small

#51 Codify 서비스 소개(사용 방법) 내용 추가(README.md)
  Codify/images/AutoDetectNHighlight.png
  Codify/images/Download.png
  Codify/images/Run.png
  Codify/images/contextMenus.png
  Codify/images/editor.gif
  Codify/images/menu.png
  Codify/images/selector.gif
  README.md
Labels: documentation

#52 코드 인식 기능의 전반적 개선
  Codify/js/codify/detect.js
  Codify/js/codify/util.browser.js
Labels: enhancement

#53 테스트 데이터 분리 후 기존 데이터 삭제
  예제링크.txt
Labels: small

#54 크로스 브라우저 호환성 개선
  Codify/js/codify/background.js
  Codify/js/codify/lib_history.js
  Codify/js/codify/nav.js
  Codify/js/codify/popup.js
  Codify/js/codify/storage.js
  Codify/js/codify/util.js
Labels: enhancement

#58 구글 폰트를 CDN 방식에서 embed 방식으로 변경하여 속도 향상
  Codify/css/google-fonts.css
  Codify/js/codify/detect.js
  Codify/manifest.json
  Codify/webfonts/Source_Code_Pro/OFL.txt
  Codify/webfonts/Source_Code_Pro/SourceCodePro-Black.ttf
  Codify/webfonts/Source_Code_Pro/SourceCodePro-Bold.ttf
  Codify/webfonts/Source_Code_Pro/SourceCodePro-ExtraLight.ttf
  Codify/webfonts/Source_Code_Pro/SourceCodePro-Light.ttf
  Codify/webfonts/Source_Code_Pro/SourceCodePro-Medium.ttf
  Codify/webfonts/Source_Code_Pro/SourceCodePro-Regular.ttf
  Codify/webfonts/Source_Code_Pro/SourceCodePro-Semibold.ttf
Labels: enhancement

#62 Editor 코드 수정 후 팝업창을 닫을 시 수정 내역이 저장되도록 구현
  Codify/js/codify/popup.js
Labels: enhancement
