Repository CAU-OSS-2019/team-project-team14, pull requests merged in 2019-06, with the labels that each got.

#64 코드 공백 인식 버그 해결 및 도메인 블랙리스트 기능 추가
  Codify/js/codify/detect.js
Labels: bugfix, enhancement, refactoring

#63 Add supported language api to server
  api-server/README.md
  api-server/server/api/urls.py
  api-server/server/api/views.py
Labels: enhancement

#65 서버에서 너무 많은 컴파일 요청을 차단하는 기능 추가 (DDoS 방어)
  api-server/server/api/migrations/0007_source_ip.py
  api-server/server/api/models.py
  api-server/server/api/utils.py
  api-server/server/api/views.py
  api-server/server/requirements.txt
Labels: enhancement

#74 파이썬 컴파일 기능 추가
  Codify/html/popup.html
  api-server/server/api/compile_tasks.py
  api-server/server/api/migrations/0005_auto_20190517_0014.py
  api-server/server/api/models.py
  api-server/server/api/views.py
  api-server/server/docker/python/Dockerfile
  api-server/server/docker/python/docker-build.sh
  api-server/server/docker/python/docker-run.sh
  api-server/server/docker/python/exec.sh
Labels: enhancement

#78 Pr/change theme
  Codify/css/codify/style_black.css
  Codify/css/codify/style_white.css
  Codify/html/history.html
  Codify/html/popup.html
  Codify/html/result.html
  Codify/js/codify/nav.js
Labels: enhancement

#79 Make setting.html and move theme change to setting.
  Codify/css/codify/style_black.css
  Codify/css/codify/style_white.css
  Codify/html/history.html
  Codify/html/popup.html
  Codify/html/result.html
  Codify/html/setting.html
  Codify/js/codify/background.js
  Codify/js/codify/html_all.js
  Codify/js/codify/nav.js
  Codify/js/codify/set_theme.js
  Codify/js/codify/settings.js
Labels: enhancement, refactoring, small
